### ISSUE TITLE
Tiny comments on Chapter 1

### ISSUE THREAD

**Issue by moewew** [PaulStanley/biblatex-tutorial#1]
Thank you very much for your wonderful work. Below are a few comments that don't warrant an issue on their own.

In https://github.com/PaulStanley/biblatex-tutorial/blob/5b88b5ac535f29c98231ac9bf6b399c38efb2341/introduction.tex#L100 `\intref{chapter:tools}` just produces 'chapter:tools', presumably some other text is expected.

Since you are loading `\csquotes` in your example https://github.com/PaulStanley/biblatex-tutorial/blob/5b88b5ac535f29c98231ac9bf6b399c38efb2341/introduction.tex#L182, why not use it instead the manual quote characters?

Maybe you could make verbatim mode more prominent by using frames or a different background colour. I especially noticed it in https://github.com/PaulStanley/biblatex-tutorial/blob/5b88b5ac535f29c98231ac9bf6b399c38efb2341/introduction.tex#L206 where more graphical 'punch' would have helped, I think.

When you mention Biber errors in  https://github.com/PaulStanley/biblatex-tutorial/blob/5b88b5ac535f29c98231ac9bf6b399c38efb2341/introduction.tex#L232 it could be a nice idea to mention `.blg` files.

You already have some links to TeX.SX questions, but when I read https://github.com/PaulStanley/biblatex-tutorial/blob/5b88b5ac535f29c98231ac9bf6b399c38efb2341/introduction.tex#L265 I immediately thought of  http://tex.stackexchange.com/q/25701/ and http://tex.stackexchange.com/q/5091/

You rightfully point out that some people don't need to switch. (https://github.com/PaulStanley/biblatex-tutorial/blob/5b88b5ac535f29c98231ac9bf6b399c38efb2341/introduction.tex#L293) You might want to mention more explicitly that many journals have their own `.bst` styles, and very few (if not none) accept `biblatex` http://tex.stackexchange.com/q/12175/

**Comment by PaulStanley** [comment]
Thanks. Very helpful comments all of them. I'm revising this weekend and I will take them all into account.


-------- Original message --------

**Comment by PaulStanley** [comment]
Taken into account in revised version which I will commit shortly.
