### ISSUE TITLE
Suggestions for Chapter 2

### ISSUE THREAD

**Issue by moewew** [PaulStanley/biblatex-tutorial#2]
Since you mention the volume 234 explicitly, you could also add it to the bibliography entry in https://github.com/PaulStanley/biblatex-tutorial/blob/837fa1577eb6d25eaa7d75c4a9daab95c87d7a19/database.tex#L471

Since the difference between `number` and `issue` is a source of confusion for many newcomers, you might want to mention in https://github.com/PaulStanley/biblatex-tutorial/blob/837fa1577eb6d25eaa7d75c4a9daab95c87d7a19/database.tex#L746 that a number will almost exclusively go into the `number` field and `issue` will only contain strings no matter if the journal calls the subdivisions of volumes issue or number. 

https://github.com/PaulStanley/biblatex-tutorial/blob/837fa1577eb6d25eaa7d75c4a9daab95c87d7a19/database.tex#L751 The `month` field is only there for backwards compatibility (like `year`). I would normally expect it to refer to the publication date and not the number of a journal.

**Comment by PaulStanley** [comment]
Thanks. All taken into account in revisions to be committed shortly.
