### ISSUE TITLE
Chapter 11 (tools.tex)

### ISSUE THREAD

**Issue by ghost** [PaulStanley/biblatex-tutorial#6]
What a great ›introduction‹ you wrote! Very nicely done in the ›Bringhurst-editing-style‹.

I was just wondering whether the third run of `pdflatex` (or `lua/xelatex`) is necessary with `biber`/`biblatex`: https://github.com/PaulStanley/biblatex-tutorial/blob/master/tools.tex#L25

**Comment by PaulStanley** [comment]
Sometimes, yes. The third run is necessary with some citation styles (for instance those that use `ibid`, IIRC. Styles such as numeric styles will usually stabilise with only one post-Biber run. But bearing in mind the audience, I'd rather suggest too many runs than too few. (Just as a `biber` run is not always necessary after amending the source; but again, better safe than sorry!)
